version: '3.9'

services:
  webapi:
    build:
      context: .
      dockerfile: src/Hosts/Otiva.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__PostgresBoardDb=Server=database;Database=Otiva;Username=postgres;Password=postgres;Port=5432
    depends_on:
      - database
    networks:
      - otiva_network

  database:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: "Otiva"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - otiva_network

volumes:
  pg-data:

networks:
  otiva_network:
